#!/bin/bash

# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth
# Also, some commands I do often but never go back through my history to
# repeat. Also I use a function called f all the time but the history isn't
# diagnostic of what I was doing). 
HISTIGNORE="cd:cl:clc:ls:l:..:...:....:sob:f *"

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt
force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

if [ "$color_prompt" = yes ]; then
    # the \n\$ at the end puts the prompt on a newline
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;35m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\n\$ '
    # PS1='${debian_chroot:+($debian_chroot)}\[\e[38;5;208m\]\u@\h\[\e[00m\]:\[\e[38;5;39m\]\w\[\e[38;5;208m\]\$\e[m '
else
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
fi

unset color_prompt force_color_prompt

# I don't want a huge path on display
PROMPT_DIRTRIM=2

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# source host specific bashrc file if it exists
[ -f ~/linux_config_files/bashrc_multihost/$HOSTNAME ] &&
source ~/linux_config_files/bashrc_multihost/$HOSTNAME
# source base bash_aliases if it exists
[ -f ~/linux_config_files/aliases_multihost/base_aliases ] &&
source ~/linux_config_files/aliases_multihost/base_aliases
# source host specific bash_aliases if they exist
[ -f ~/linux_config_files/aliases_multihost/$HOSTNAME ] &&
source ~/linux_config_files/aliases_multihost/$HOSTNAME
# source base bash_functions if it exists
[ -f ~/linux_config_files/functions_multihost/base_functions ] &&
source ~/linux_config_files/functions_multihost/base_functions
# source host specific bash_functions if they exist
[ -f ~/linux_config_files/functions_multihost/$HOSTNAME ] &&
source ~/linux_config_files/functions_multihost/$HOSTNAME

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# use vi shortcuts in terminal
set -o vi
# make vim my default editor
export VISUAL=vim
export EDITOR=$VISUAL

# disable flow control for that terminal completely (to prevent Crtl-s 
# https://unix.stackexchange.com/questions/12107/
# how-to-unfreeze-after-accidentally-pressing-ctrl-s-in-a-terminal)
stty -ixon

# Apparently a bad idea to do this: https://blog.sanctum.geek.nz/term-strings/
# TERM=xterm-256color  	# I need this to happen before tmux launches 
			            # - it allows the cursor to reflect vi(m) mode

# set capslock to escape key  
setxkbmap -option ‘caps:ctrl_modifier’
setxkbmap -option ctrl:nocaps
xcape -e '#66=Escape'

# Launch tmux
if command -v tmux>/dev/null; then
    [[ ! $TERM =~ screen ]] && [ -z $TMUX ] && tmux new-session -A -s main

    # check if we have been switched to dark, else go light
    [[ ! $(tmux show-environment | grep THEME) =~ 'THEME=dark' ]] &&
    tmux set-environment THEME light 
fi

# set IPs as variables so I don't have to look them up all the time
gla='gpuws4-pc.psy.gla.ac.uk'
pony='130.104.83.192'
cism='mbennett@storage.cism.ucl.ac.be'

# Install Ruby Gems to ~/gems
export GEM_HOME="$HOME/gems"
export PATH="$HOME/gems/bin:$PATH"

# todo path
export TODO_PATH='/home/mattb/documents/work_notes/.todo'

### fzf config ################################################################
# fzf setup
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
# Appearance: Don't fill the terminal with results. Have the best matches at
# the top. Selected items have a bean marker
fzf1='--height 40% -m --layout=reverse --marker=o'
# CTRL-A to select all items found, CTRL-D to deselect all
fzf2='--bind ctrl-a:select-all,ctrl-d:deselect-all'
# scroll the preview window
fzf3='--bind ctrl-y:preview-up,ctrl-e:preview-down'

# enter the above into one long string
export FZF_DEFAULT_OPTS="${fzf1} ${fzf2} ${fzf3}"

