#!/bin/sh

# grabbed these from the .bashrc
# enable color support of ls and also add handy aliases
 if [ -x /usr/bin/dircolors ]; then
     test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
 	alias ls='ls --color=auto'
 fi	

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'


#### my own aliases ###########################################################
alias cl='clear && clear'
alias clc='clear && clear'

# move up 1,2 or 3 directories
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'

# show ls vertically by default using the -1 switch
alias l='ls -1 -hF'
# same as above, but with file details too
alias ll='ls -lhF'
# same as above, but with hidden files too
alias lll='ls -alhF'

# only list directories
alias ld='ls -1 -d */'
# same as above, but with file details too
alias lld='ls -ld */'

# same but sort by date modified
alias lt="(tput rmam; ls -1 -hF; tput smam)"
# I wanted the two below to show the list sorted by date modified but they're
# not working right
# alias llt="(tput rmam; ls -lhF; tput smam)"
# alias lllt="(tput rmam; ls -alhF; tput smam)"

alias untar='tar zxvf'

# common places to cd, pipe the dir and subdirs (to a given depth) into fzf
cdu_arg='cd $(( ls -d  /media/mattb/usb/; \
                ls -d  /media/mattb/usb/*/; \
                ls -d  /media/mattb/usb/*/*/) \
                | grep -v .git | fzf)'

alias cdu=${cdu_arg}

# removed and restore fzf default options (if I want to use it in an usual directory)
alias fzfcl="export FZF_DEFAULT_COMMAND='fd .'"
alias fzf-="export FZF_DEFAULT_COMMAND='fd . $HOME'"

# source .bashrc
alias sob='source ~/.bashrc'
# edit dot files
alias ea='vim ~/linux_config_files/aliases_multihost/base_aliases'
alias eb='vim ~/linux_config_files/base_bashrc'
alias ev='vim ~/linux_config_files/vimrc'
alias et='vim ~/linux_config_files/tmux.conf'

# kill tmux
alias kt='tmux kill-session -t main'
# switch between light and dark themes
alias ol="tmux source-file ~/.tmux_light.conf; tmux set-environment THEME 'light'"
alias od="tmux source-file ~/.tmux_dark.conf; tmux set-environment THEME 'dark'"

# w3m
alias wm="w3m www.google.com"

# git
alias gitlog="git log --graph --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)%an%C(reset) %C(bold yellow)%d%C(reset)' -n5"

# open matlab in the termainal
alias matlabnd='/usr/local/MATLAB/R2019b/bin/matlab -nodesktop -nosplash'
# with vi shortcuts
alias vmatlabnd='rlwrap -a matlab -nodesktop -nosplash'

# open R with vi shortcuts
alias vr='rlwrap -a R'

# in case I start getting errors popping up in the terminal,
# automatically open a new tmux window:
alias chrome='google-chrome & tmux new-window'

# access to contents of system clipboard (commands I plan on using start with this form)
alias clip='xclip -selection clipboard'

# set night light temp (default=4000)
alias day='gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 5000'
alias eve='gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 4000'
alias night='gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 3000'

# ssh conenctions
# access the pony with or without X11 Forwarding
alias sshpony='ssh mattb@130.104.83.192'
alias sshponyx='ssh -X mattb@130.104.83.192'
# CISM mass storage
alias sshcism='ssh mbennett@storage.cism.ucl.ac.be'
# Glasgow
alias sshgla='ssh gpuws4-pc.psy.gla.ac.uk'
alias sshglax='ssh -X gpuws4-pc.psy.gla.ac.uk'

# connect or dissconnect to UCLouvain vpn
alias uvc='nmcli con up ae483762-6fb0-49b0-a450-a280099d5eb8 UCL'
alias uvd='nmcli con down ae483762-6fb0-49b0-a450-a280099d5eb8 UCL'

# connect or dissconnect to Glasgow vpn
alias gvc='nmcli con up 8b9c5955-9ba5-42c7-bdc4-9464ec4f2a49 Glasgow'
alias gvd='nmcli con down 8b9c5955-9ba5-42c7-bdc4-9464ec4f2a49 Glasgow'

