#!/bin/sh

# grabbed these from the .bashrc
# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
fi

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'


#### my own aliases ###########################################################
alias cl='clear && sleep 0.001 && clear'
alias clc='clear && sleep 0.001 && clear'
alias c='cd && clear && sleep 0.001 && clear'

# move up 1,2 or 3 directories
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'

# show ls vertically by default using the -1 switch
alias l='ls -1 -hF'
# same as above, but with file details too
alias ll='ls -lhF'
# same as above, but with hidden files too
alias lll='ls -alhF'

# only list directories
alias ld='ls -1 -d */'
# same as above, but with file details too
alias lld='ls -ld */'

# same but sort by date modified
alias lt="(tput rmam; ls -1 -hF; tput smam)"
# I wanted the two below to show the list sorted by date modified but they're
# not working right
# alias llt="(tput rmam; ls -lhF; tput smam)"
# alias lllt="(tput rmam; ls -alhF; tput smam)"

alias untar='tar zxvf'

# I can't spell
alias mdkir='mkdir'

# source .bashrc
alias sob='source ~/.bashrc'

# edit dot files (using my v for vim function)
alias et='v ~/linux_config_files/tmux.conf'
alias ev='v ~/linux_config_files/vimrc'
alias ez='v ~/linux_config_files/zathurarc'

# generate aliases to open host specific dot files (using v function)
declare -A dir_dict=([eb]=bashrc_ [ea]=aliases_ [ef]=functions_)
declare -A file_dict=([b]=base [f]=flat [l]=laptop [o]=office [d]=dapony)
for dir_abbrv in "${!dir_dict[@]}"
do
    for file_abbrv in "${!file_dict[@]}"
    do
        alias $dir_abbrv$file_abbrv="v ~/linux_config_files/${dir_dict[$dir_abbrv]}multihost/${file_dict[$file_abbrv]}"
    done
done

# kill tmux
alias kt='tmux kill-session -t main'
# switch between light and dark themes
alias ol="tmux source-file ~/.tmux_light.conf; tmux set-environment THEME 'light'; export BAT_THEME='Monokai Extended Light'"
alias od="tmux source-file ~/.tmux_dark.conf; tmux set-environment THEME 'dark'; export BAT_THEME=''"

# w3m
alias wm="w3m www.google.com"

# git
alias gitlog="git log --graph --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)%an%C(reset) %C(bold yellow)%d%C(reset)' -n5"

# open matlab in the termainal
alias matlabnd='/usr/local/MATLAB/R2019b/bin/matlab -nodesktop -nosplash'
# with vi shortcuts
alias vmatlabnd='rlwrap -a matlab -nodesktop -nosplash'
# open R with vi shortcuts
alias vr='rlwrap -a R'
# open python3
alias py='python3'

alias zathura='zathura --mode fullscreen'

# in case I start getting errors popping up in the terminal,
# automatically open a new tmux window:
alias chrome='google-chrome & tmux new-window'

# access to contents of system clipboard (commands I plan on using start with this form)
alias clip='xclip -selection clipboard'

# set night light temp (default=4000) (<2530 causes flickering on flat monitor)
alias day='gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 5000'
alias eve='gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 3750'
alias night='gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature 2575'

# ssh conenctions
# access the pony with or without X11 Forwarding
alias sshpony='ssh mattb@130.104.83.192'
alias sshponyx='ssh -X mattb@130.104.83.192'
# access jolien's pc with or without X11 Forwarding
alias sshjolien='ssh mattb@130.104.83.35'
alias sshjolienx='ssh -X mattb@130.104.83.35'
# CISM mass storage
alias sshcism='ssh mbennett@storage.cism.ucl.ac.be'
# Glasgow
alias sshgla='ssh gpuws4-pc.psy.gla.ac.uk'
alias sshglax='ssh -X gpuws4-pc.psy.gla.ac.uk'

# connect or dissconnect to UCLouvain vpn
alias uvc='nmcli con up ae483762-6fb0-49b0-a450-a280099d5eb8 UCL'
alias uvd='nmcli con down ae483762-6fb0-49b0-a450-a280099d5eb8 UCL'

# connect or dissconnect to Glasgow vpn
alias gvc='nmcli con up 8b9c5955-9ba5-42c7-bdc4-9464ec4f2a49 Glasgow'
alias gvd='nmcli con down 8b9c5955-9ba5-42c7-bdc4-9464ec4f2a49 Glasgow'

