#!/bin/bash

alias sd='shutdown'

# ufc
alias ufc='cat ~/videos/ufc/ufc_database.txt | fzf | sort'
alias ufcud='python3 /home/mattb/code/python/python_flat/random/ufc_database.py' 

# motivation to train
alias mma='vlc --random --loop --fullscreen ~/videos/mma_highlights/*.mp4 &'

# # display the ufc video I am watching/should watch next
# alias ufc='path="/home/mattb/videos/ufc/"; \
# 	current_vid="$(ls ${path} | grep -vi watched | grep -vi cancelled | head -n1)"; \
# 	echo "${current_vid}"'

# # play the vid found above in fullscreen mode
# alias ufcp='ufc; vlc -f "${path}${current_vid}" &'

# # add '_Watched' at the end of the file name
# alias ufcr='mv ${path}${current_vid} ${path}${current_vid::-4}_Watched${current_vid: -4} && echo "next up:" && ufc'

# launch utorrent server
alias ut='utserver -settingspath /usr/local/utorrent-server-alpha-v3_3/ &'
alias wcut='windscribe connect && utserver -settingspath /usr/local/utorrent-server-alpha-v3_3/ &'
alias wdut='pkill utserver && windscribe disconnect'

# read book
alias nerd='zathura ~/documents/books/linux/UNIX*.pdf &'
alias linal='zathura  ~/documents/books/maths/strang_g_introduction_to_linear_algebra_5th_ed_solutions/c01.pdf ~/documents/books/maths/strang_g_introduction_to_linear_algebra_5th_ed.pdf &'

# compose stack answers in a separate window, with 3 splits and vim ready to go
alias st="tmux new-window -n 'stack';\
    tmux send-keys -t 'stack' 'cd ~/stack;\
    tmux split-window -h;\
    tmux split-window -v;\
    vim -o your_file answers/new.md' Enter"

alias kst='tmux kill-window -t stack'

# plot typing speed
alias tc='python3 ~/code/python/python_flat/speed.py &'

# show pressed keys onscreen for vim youtube videos
alias vidkeydisp='screenkey/./screenkey -p fixed -g 750x100+1100+825 &'
