#!/bin/bash

alias sd='shutdown'

alias fo='cat ~/focus'
# removed and restore fzf default options (if I want to use it in an usual directory)
alias fzfcl="export FZF_DEFAULT_COMMAND='fd .'"
alias fzf-="export FZF_DEFAULT_COMMAND='fd . $HOME'"

# watch a secret film
alias sf='source /home/mattb/code/bash/play_secret_film.sh'

# ufc
alias ufc='cat ~/videos/ufc/ufc_database.txt | fzf | sort'
alias ufcud='python3 /home/mattb/code/python/python_flat/random/ufc_database.py' 

alias vlc='vlc "$@" 2>/dev/null'

# motivation to train
alias mma='vlc --random --loop --fullscreen ~/videos/mma_highlights/*.mp4 &'

# play all the music
alias mu='vlc ~/music/[^hitchhiker]*/*mp3 &'
alias jp='vlc ~/music/jurassic-park-theme-song-made-with-Voicemod.mp3 &'


# # display the ufc video I am watching/should watch next
# alias ufc='path="/home/mattb/videos/ufc/"; \
# 	current_vid="$(ls ${path} | grep -vi watched | grep -vi cancelled | head -n1)"; \
# 	echo "${current_vid}"'

# # play the vid found above in fullscreen mode
# alias ufcp='ufc; vlc -f "${path}${current_vid}" &'

# # add '_Watched' at the end of the file name
# alias ufcr='mv ${path}${current_vid} ${path}${current_vid::-4}_Watched${current_vid: -4} && echo "next up:" && ufc'

# launch utorrent server
alias ut='utserver -settingspath /opt/utorrent-server-alpha-v3_3/ &'
alias wcut='windscribe connect && utserver -settingspath /opt/utorrent-server-alpha-v3_3/ &'
alias wdut='pkill utserver && windscribe disconnect; windscribe account'

# practice R coding
alias lr="
    tmux new-window -n 'advanced_r'
    tmux split-window -h
    tmux send-keys -t 'main:advanced_r.2' 'cd /home/mattb/code/r/learning_r/advanced_r' Enter
    tmux send-keys -t main:advanced_r.2 'vim -o exercises_ch08.R scratch.R' Enter
    tmux send-keys -t main:advanced_r.2 ':call ChangeBufferSlimeConfig(200, 1)' Enter
    tmux send-keys -t main:advanced_r.2 'G' Enter
    tmux send-keys -t main:advanced_r.2 ':wincmd j' Enter
    tmux send-keys -t main:advanced_r.2 ':resize 10' Enter
    tmux send-keys -t main:advanced_r.2 ':call ChangeBufferSlimeConfig(200, 1)' Enter
    tmux send-keys -t main:advanced_r.2 'ss' Enter
    tmux send-keys -t main:advanced_r.2 'sap' Enter
    tmux send-keys -t main:advanced_r.2 ':e README.md' Enter
    tmux send-keys -t main:advanced_r.2 ':wincmd k' Enter
    tmux send-keys -t 'main:advanced_r.1' 'cd /home/mattb/code/r/learning_r/advanced_r' Enter
    tmux send-keys -t main:advanced_r.1 'R' Enter
    " 

alias klr='tmux kill-window -t advanced_r'

# in case I want to have the split of a particular size, use this
# tmux split-window -vb -l 5;\

# compose stack answers in a separate window, with 3 splits and vim ready to go
alias st="tmux new-window -n 'stack';\
    tmux send-keys -t 'stack' 'cd ~/stack;\
    tmux split-window -h;\
    tmux split-window -v;\
    vim -o your_file answers/new.md' Enter
    "

alias kst='tmux kill-window -t stack'


    # vim -o rethinking.R scratch1.R' Enter"

# plot typing speed
alias tc='python3 ~/code/python/python_flat/speed.py &'

# show pressed keys onscreen for vim youtube videos
alias vidkeydisp='~/videos/vim/screenkey/screenkey -p fixed -g 750x100+1100+825 &'

# for when I want to make a gif of something in vim
alias vimgif='vim -u ~/dotfiles/plugin_showcase.vim'

# for when I want to make a gif of something in vim
alias books='rsync -avz -e ssh ~/documents/books mattb@192.168.0.24:Documents/'



