#!/bin/bash

alias sd='shutdown'

# removed and restore fzf default options (if I want to use it in an usual directory)
alias fzfcl="export FZF_DEFAULT_COMMAND='fd .'"
alias fzf-="export FZF_DEFAULT_COMMAND='fd . $HOME'"

# ufc
alias ufc='cat ~/videos/ufc/ufc_database.txt | fzf | sort'
alias ufcud='python3 /home/mattb/code/python/python_flat/random/ufc_database.py' 

# motivation to train
alias mma='vlc --random --loop --fullscreen ~/videos/mma_highlights/*.mp4 &'

# play all the music
alias mu='vlc ~/music/[^hitchhiker]*/*mp3 &'

# # display the ufc video I am watching/should watch next
# alias ufc='path="/home/mattb/videos/ufc/"; \
# 	current_vid="$(ls ${path} | grep -vi watched | grep -vi cancelled | head -n1)"; \
# 	echo "${current_vid}"'

# # play the vid found above in fullscreen mode
# alias ufcp='ufc; vlc -f "${path}${current_vid}" &'

# # add '_Watched' at the end of the file name
# alias ufcr='mv ${path}${current_vid} ${path}${current_vid::-4}_Watched${current_vid: -4} && echo "next up:" && ufc'

# launch utorrent server
alias ut='utserver -settingspath /opt/utorrent-server-alpha-v3_3/ &'
alias wcut='windscribe connect && utserver -settingspath /opt/utorrent-server-alpha-v3_3/ &'
alias wdut='pkill utserver && windscribe disconnect; windscribe account'

# practice R coding
alias rds="zathura /home/mattb/documents/books/data_science/r_for_data_science_wickham_and_grolemund_2017.pdf &
    tmux new-window -n 'r_for_data_science'
    tmux split-window -v
    tmux send-keys -t 'main:r_for_data_science.1' 'cd /home/mattb/code/r/r_for_data_science' Enter
    tmux send-keys -t main:r_for_data_science.1 'vim -O exercises_ch16.R scratch.R' Enter
    tmux send-keys -t main:r_for_data_science.1 ':call ChangeBufferSlimeConfig(200, 2)' Enter
    tmux send-keys -t main:r_for_data_science.1 ':vertical resize 90' Enter
    tmux send-keys -t main:r_for_data_science.1 ':wincmd l' Enter
    tmux send-keys -t main:r_for_data_science.1 ':call ChangeBufferSlimeConfig(200, 2)' Enter
    tmux send-keys -t main:r_for_data_science.1 'ss' Enter
    tmux send-keys -t main:r_for_data_science.1 'sap' Enter
    tmux send-keys -t 'main:r_for_data_science.2' 'cd /home/mattb/code/r/r_for_data_science' Enter
    tmux send-keys -t main:r_for_data_science.2 'R' Enter
    " 

alias krds='pkill zathura; tmux kill-window -t r_for_data_science'

# in case I want to have the split of a particular size, use this
# tmux split-window -vb -l 5;\

# compose stack answers in a separate window, with 3 splits and vim ready to go
alias st="tmux new-window -n 'stack';\
    tmux send-keys -t 'stack' 'cd ~/stack;\
    tmux split-window -h;\
    tmux split-window -v;\
    vim -o your_file answers/new.md' Enter
    "

alias kst='tmux kill-window -t stack'


    # vim -o rethinking.R scratch1.R' Enter"

# plot typing speed
alias tc='python3 ~/code/python/python_flat/speed.py &'

# show pressed keys onscreen for vim youtube videos
alias vidkeydisp='~/videos/vim/screenkey/screenkey -p fixed -g 750x100+1100+825 &'

# for when I want to make a gif of something in vim
alias vimgif='vim -u ~/dotfiles/plugin_showcase.vim'
