#!/bin/bash

alias sd='shutdown'

alias skype='skypeforlinux &'

# launch utorrent server
alias ut='utserver -settingspath /opt/utorrent-server-alpha-v3_3/ &'

# show pressed keys onscreen for vim youtube videos
#alias vidkeydisp='screenkey/./screenkey -p fixed -g 90%x10%+5%-10%'

# set night light temp (default=4000)
alias day='redshift -PO 3500'
alias eve='redshift -O 2500'
alias night='redshift -O 1500'
