#!/bin/bash

# removed and restore fzf default options (if I want to use it in an usual directory)
alias fzfcl="export FZF_DEFAULT_COMMAND='fdfind .'"
alias fzf-="export FZF_DEFAULT_COMMAND='fdfind . $HOME'"

