#!/bin/bash

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/mattb/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/mattb/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/mattb/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/mattb/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

# disable mouse scrolling (since my wireless mouse wheel is crazy)
wireless_mouse_id=$(xinput list | awk '/2\.4G.*Mouse/ {print $9}' | sed 's/id=//')
xinput set-button-map $wireless_mouse_id 1 2 3 0 0

# fzf config: debian has a different binary name
export FZF_DEFAULT_COMMAND="fd . $HOME"

# so I can use ttygif (https://github.com/icholy/ttygif)
export WINDOWID=$(xdotool getwindowfocus)

# connect or dissconnect to UCLouvain vpn
alias uvc='openvpn3 session-start --config downloads/profile-10367.ovpn'
alias uvd='openvpn3 session-manage --config downloads/profile-10367.ovpn --disconnect'
