#!/bin/bash

# Run command/application and choose paths/files with fzf.
# Always return control of the terminal to user (e.g. when opening GUIs).
# The full command that was used will appear in your history just like any
# other (N.B. to achieve this I write the shell's active history to
# ~/.bash_history)
#
# Usage:
# f cd [OPTION]... (hit enter, choose path)
# f cat [OPTION]... (hit enter, choose files)
# f vim [OPTION]... (hit enter, choose files)
# f vlc [OPTION]... (hit enter, choose files)

# synch bat theme with overall dark/light theme
set_bat_theme() {
    if [[ $(tmux show-environment THEME) == THEME=light ]] ;
    then
        export BAT_THEME='Monokai Extended Light'
    else
        export BAT_THEME=''
    fi
    }

f() {
    # ensure bat colours are correct
    set_bat_theme

    # if no arguments passed, just lauch fzf
    if [ $# -eq 0 ]
    then
        fzf | sort
        return 0
    fi

    # store the program
    program="$1"

    # remove first argument off the list
    shift

    # store any option flags
    options="$@"

    # store the arguments from fzf
    arguments=$(fzf --multi)

    # if no arguments passed (e.g. if Esc pressed), return to terminal
    if [ -z "${arguments}" ]; then
        return 1
    fi

    # sanitise the command:
    # put an extra single quote next to any pre-existing single quotes
    # put single quotes around each argument
    # put them all on one line.
    for arg in "${arguments[@]}"; do
        arguments=$(echo "$arg" | sed "s/'/''/g;
                                       s/.*/'&'/g;
                                       s/\n//g"
                   )
    done

    # if the program is on the GUI list, add a '&'
    if [[ "$program" =~ ^(nautilus|zathura|evince|vlc|eog|kolourpaint)$ ]]; then
        arguments="$arguments &"
    fi

    # write the shell's active history to ~/.bash_history.
    history -w

    # add the command with the sanitised arguments to .bash_history
    echo $program $options $arguments >> ~/.bash_history

    # reload the ~/.bash_history into the shell's active history
    history -r

    # execute the last command in history
    fc -s -1
    }

# cat but just cut at edge of tmux pane instead of wrapping lines
catc () {
    width=$(tmux display-message -p '#{pane_width}')
    options="$@"
    cat $options | cut -c -$(($width-3))
    }

temp () {
    gsettings set org.gnome.settings-daemon.plugins.color night-light-temperature $1
    }

# wrapper for bash script (passes all arguments)
# also displays todo list with numbers
todo () {
    options="$@"
    ~/todo/./todo.sh $options
    catc -n $TODO_PATH/master_todo.md
    }

# mkdir and cd into it
mkdircd () {
    mkdir -p $1 && cd $1
    }

apa () {
    rename 'y/A-Z/a-z/' *.pdf
    rename 's/ /_/g' *.pdf
    rename 's/_.\.//g' *.pdf
    rename 's/,//g' *.pdf
    rename 's/\)\._/)_/g' *.pdf
    rename 's/\._/_[/g' *.pdf
    rename 's/\)\./)]\./g' *.pdf
    rename 's/_&//g' *.pdf
    rename 's/:/-/g' *.pdf
    }

cleanname () {
    rename 'y/A-Z/a-z/' *
    rename 's/ /_/g' *
    rename "s/'//g" *
    rename 's/,//g' *
    rename 's/\./_/g' *  
    rename 's/_pdf/.pdf/g' *  
    # rename 's/_\w+$/.test/g' *
    }

