#!/bin/bash

# if on nhs machine, just default to vim
v () {
    arguments="$@"
    vim $arguments
    }

# toggle the R Graphics window but leave control in the terminal
function ff () {
    # echo $(xprop -id "$(xdotool search --name Graphics)" _NET_WM_STATE)
    if [[ $(xprop -id "$(xdotool search --name Graphics)" _NET_WM_STATE) == '_NET_WM_STATE(ATOM) = _NET_WM_STATE_BELOW' ]]; 
    then 
    # echo hello
        xdotool search --name Graphics windowstate --remove BELOW
        xdotool search --name Graphics windowstate --add ABOVE
    else
    # echo world
        xdotool search --name Graphics windowstate --remove ABOVE
        xdotool search --name Graphics windowstate --add BELOW
    fi
}
